/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gui.absensi;

/**
 *
 * @author ASUS
 */
public class ABSENSIGUI extends javax.swing.JFrame {
    
    String nama, nim, alamat, tinggal, prodi, hobi, gender;

    /**
     * Creates new form ABSENSIGUI
     */
    public ABSENSIGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TXTtitle = new javax.swing.JLabel();
        TXThobi = new javax.swing.JLabel();
        TxtNama = new javax.swing.JLabel();
        TFhobby = new javax.swing.JTextField();
        TFnama = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        AreaOutput = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        TFnim = new javax.swing.JTextField();
        BTNsubmit = new javax.swing.JButton();
        TXTgender = new javax.swing.JLabel();
        TXTtinggal = new javax.swing.JLabel();
        CMBgender = new javax.swing.JComboBox<>();
        TFtinggal = new javax.swing.JTextField();
        TXTprodi = new javax.swing.JLabel();
        CMBprodi = new javax.swing.JComboBox<>();
        TXTalamat = new javax.swing.JLabel();
        BTNhapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaAlamat = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TXTtitle.setBackground(new java.awt.Color(0, 51, 51));
        TXTtitle.setFont(new java.awt.Font("Old English Text MT", 1, 48)); // NOI18N
        TXTtitle.setForeground(new java.awt.Color(102, 0, 102));
        TXTtitle.setText("Biodata Mahasiswa");

        TXThobi.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        TXThobi.setForeground(new java.awt.Color(51, 0, 51));
        TXThobi.setText("Hobi");

        TxtNama.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        TxtNama.setForeground(new java.awt.Color(51, 0, 51));
        TxtNama.setText("Nama");

        TFhobby.setBackground(new java.awt.Color(255, 153, 102));
        TFhobby.setForeground(new java.awt.Color(102, 0, 102));
        TFhobby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFhobbyActionPerformed(evt);
            }
        });

        TFnama.setBackground(new java.awt.Color(255, 153, 102));
        TFnama.setForeground(new java.awt.Color(102, 0, 102));
        TFnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFnamaActionPerformed(evt);
            }
        });

        AreaOutput.setBackground(new java.awt.Color(255, 153, 102));
        AreaOutput.setColumns(20);
        AreaOutput.setForeground(new java.awt.Color(102, 0, 102));
        AreaOutput.setRows(5);
        AreaOutput.setText("Output\n");
        jScrollPane2.setViewportView(AreaOutput);

        jLabel1.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 51));
        jLabel1.setText("NIM");

        TFnim.setBackground(new java.awt.Color(255, 153, 102));
        TFnim.setForeground(new java.awt.Color(102, 0, 102));
        TFnim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFnimActionPerformed(evt);
            }
        });

        BTNsubmit.setBackground(new java.awt.Color(102, 0, 102));
        BTNsubmit.setFont(new java.awt.Font("STSong", 1, 14)); // NOI18N
        BTNsubmit.setForeground(new java.awt.Color(204, 51, 0));
        BTNsubmit.setText("KIRIM");
        BTNsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNsubmitActionPerformed(evt);
            }
        });

        TXTgender.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        TXTgender.setForeground(new java.awt.Color(51, 0, 51));
        TXTgender.setText("Gender");

        TXTtinggal.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        TXTtinggal.setForeground(new java.awt.Color(51, 0, 51));
        TXTtinggal.setText("Asal");

        CMBgender.setBackground(new java.awt.Color(255, 153, 102));
        CMBgender.setForeground(new java.awt.Color(102, 0, 102));
        CMBgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "..........", "MEN", "WOMEN" }));
        CMBgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CMBgenderActionPerformed(evt);
            }
        });

        TFtinggal.setBackground(new java.awt.Color(255, 153, 102));
        TFtinggal.setForeground(new java.awt.Color(102, 0, 102));
        TFtinggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFtinggalActionPerformed(evt);
            }
        });

        TXTprodi.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        TXTprodi.setForeground(new java.awt.Color(51, 0, 51));
        TXTprodi.setText("Prodi");

        CMBprodi.setBackground(new java.awt.Color(255, 153, 102));
        CMBprodi.setForeground(new java.awt.Color(102, 0, 102));
        CMBprodi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "..........", "TI", "SK", "MANAJEMEN", "IBM", "DKV" }));

        TXTalamat.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        TXTalamat.setForeground(new java.awt.Color(51, 0, 51));
        TXTalamat.setText("Alamat");

        BTNhapus.setBackground(new java.awt.Color(102, 0, 102));
        BTNhapus.setFont(new java.awt.Font("STSong", 1, 14)); // NOI18N
        BTNhapus.setForeground(new java.awt.Color(204, 51, 0));
        BTNhapus.setText("HAPUS");
        BTNhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNhapusActionPerformed(evt);
            }
        });

        AreaAlamat.setBackground(new java.awt.Color(255, 153, 102));
        AreaAlamat.setColumns(20);
        AreaAlamat.setForeground(new java.awt.Color(102, 0, 102));
        AreaAlamat.setRows(5);
        jScrollPane1.setViewportView(AreaAlamat);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXTalamat)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BTNhapus)
                                    .addComponent(BTNsubmit))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(TFnama, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(CMBprodi, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(TXTprodi))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CMBgender, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TFnim, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(TXTgender)))
                            .addComponent(TxtNama))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TFhobby, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TXTtinggal))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TFtinggal, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TXThobi))
                                .addGap(0, 0, Short.MAX_VALUE))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(TXTtitle)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(TXTtitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtNama)
                    .addComponent(jLabel1)
                    .addComponent(TXTtinggal, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFnama, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFnim, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFhobby, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTprodi)
                    .addComponent(TXTgender)
                    .addComponent(TXThobi))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFtinggal, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CMBgender, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CMBprodi, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(TXTalamat)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTNsubmit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTNhapus)))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFhobbyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFhobbyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFhobbyActionPerformed

    private void TFnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFnamaActionPerformed

    private void TFnimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFnimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFnimActionPerformed

    private void BTNsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNsubmitActionPerformed
        // TODO add your handling code here:
        nama = TFnama.getText();
        alamat = AreaAlamat.getText();
        gender = CMBgender.getSelectedItem().toString();
        nim = TFnim.getText();
        hobi = TFhobby.getText();
        tinggal = TFtinggal.getText();
        prodi = CMBprodi.getSelectedItem().toString();

        AreaOutput.setText("Nama: \t = " + nama + "\nGender \t= " + gender + "\nNIM \t= " + nim + "\nProdi \t= " + prodi + "\ntinggal \t= " + tinggal + "\nhobi \t= " + hobi + "\nAlamat \t= " + alamat);
    }//GEN-LAST:event_BTNsubmitActionPerformed

    private void CMBgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CMBgenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CMBgenderActionPerformed

    private void TFtinggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFtinggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFtinggalActionPerformed

    private void BTNhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNhapusActionPerformed
        // TODO add your handling code here:
        TFnim.setText("");
        TFnama.setText("");
        AreaAlamat.setText("");
        TFtinggal.setText("");
        TFhobby.setText("");
        AreaOutput.setText("");
        CMBgender.setSelectedItem("None");
        CMBprodi.setSelectedItem("None");

    }//GEN-LAST:event_BTNhapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ABSENSIGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ABSENSIGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ABSENSIGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ABSENSIGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ABSENSIGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaAlamat;
    private javax.swing.JTextArea AreaOutput;
    private javax.swing.JButton BTNhapus;
    private javax.swing.JButton BTNsubmit;
    private javax.swing.JComboBox<String> CMBgender;
    private javax.swing.JComboBox<String> CMBprodi;
    private javax.swing.JTextField TFhobby;
    private javax.swing.JTextField TFnama;
    private javax.swing.JTextField TFnim;
    private javax.swing.JTextField TFtinggal;
    private javax.swing.JLabel TXTalamat;
    private javax.swing.JLabel TXTgender;
    private javax.swing.JLabel TXThobi;
    private javax.swing.JLabel TXTprodi;
    private javax.swing.JLabel TXTtinggal;
    private javax.swing.JLabel TXTtitle;
    private javax.swing.JLabel TxtNama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
